blueprint:
  name: "Puerta abierta"
  description: "En caso de puerta abierta durante màs de 5min: Notificación + Parpadeo ROJO 30s"
  domain: automation
  input:
    contact_sensor:
      name: "Sensor puerta"
      selector:
        entity:
          domain: binary_sensor
    lights:
      name: "Luces afectadas"
      selector:
        target:
          entity:
            domain: light
    notify_actions:
      name: "Enviar notificación al móvil (puedes añadir varios)"
      description: "Busca 'mobile_' en la barra de busqueda y selecciona un mòvil"
      selector:
        action: {}
      default: []

mode: restart

trigger:
  - platform: state
    entity_id: !input contact_sensor
    to: "on"
    for:
      minutes: 5

action:
  # Immediate notification
  - !input notify_actions

  # Flashing red light 30s (0.5 on / 0.5 off -> 30 cycles)
  - repeat:
      count: 30
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            rgb_color: [255, 0, 0]
            brightness_pct: 100
        - delay:
            milliseconds: 500
        - service: light.turn_off
          target: !input lights
        - delay:
            milliseconds: 500

  # Reset lights
  - service: light.turn_on
    target: !input lights
    data:
      kelvin: 2700
      brightness_pct: 100
  - delay:
      seconds: 1
  - service: light.turn_off
    target: !input lights
