blueprint:
  name: "Lavadora"
  description: "Detecta inicio por consumo, espera fin y avisa: Notificaci칩n + Verde 5 min"
  domain: automation
  input:
    power_sensor:
      name: "Sensor potencia (W)"
      selector:
        entity:
          domain: sensor
    lights:
      name: "Luces afectadas"
      selector:
        target:
          entity:
            domain: light
    notify_actions:
      name: "Enviar notificaci칩n al m칩vil (puedes a침adir varios)"
      description: "Selecciona notify.mobile_app_..."
      selector:
        action: {}
      default: []

mode: restart

# Fixed values
# start: >12W during 20s
# stop: <4W during 4min
trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    above: 12
    for:
      seconds: 20

action:
  # Wait for it to actually finish (if it doesn't finish within 6h, it is silently cancelled)
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: !input power_sensor
        below: 4
        for:
          minutes: 4
    timeout:
      hours: 6
    continue_on_timeout: false

  # Immediate notification
  - !input notify_actions

  # Fixed green light during 5min
  - service: light.turn_on
    target: !input lights
    data:
      rgb_color: [0, 255, 0] # Green
      brightness_pct: 100
  - delay:
      minutes: 5

  # Reset lights
  - service: light.turn_on
    target: !input lights
    data:
      kelvin: 2700
      brightness_pct: 100
  - delay:
      seconds: 1
  - service: light.turn_off
    target: !input lights

