blueprint:
  name: "Fuga de agua"
  description: "En caso de fuga: Notificación + Parpadeo AZUL 30s"
  domain: automation
  input:
    leak_sensor:
      name: "Sensor de fuga"
      selector:
        entity:
          domain: binary_sensor
    lights:
      name: "Luces afectadas"
      selector:
        target:
          entity:
            domain: light
    notify_actions:
      name: "Enviar notificación al móvil"
      description: "Selecciona notify.mobile_app_..."
      selector:
        action: {}
      default: []

mode: single

trigger:
  - platform: state
    entity_id: !input leak_sensor
    to: "on"

action:
  # Immediate notification
  - !input notify_actions

  # Flashing blue light 30s
  - repeat:
      count: 30
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            rgb_color: [0, 80, 255]
            brightness_pct: 100
        - delay:
            milliseconds: 500
        - service: light.turn_off
          target: !input lights
        - delay:
            milliseconds: 500

  # Reset lights
  - service: light.turn_on
    target: !input lights
    data:
      kelvin: 2700
      brightness_pct: 100
  - delay:
      seconds: 1
  - service: light.turn_off
    target: !input lights
